export const SITE = {
  title: "Brava 94.9",
  description:
    "Tu dosis diaria de buena vibra, hits que explotan y programas que marcan tendencia.",
  url: "https://fm-brava.vercel.app/",
  defaultImage: "/image.png",
  locale: "es_AR",
  keywords: [
    "FM Brava Mendoza",
    "Brava 94.9 en vivo",
    "escuchar FM Brava online",
    "radio juvenil Mendoza",
    "la radio de tus temazos",
    "radio con más energía positiva",
    "hits urbanos Mendoza",
    "reggaeton Mendoza radio",
    "pop urbano Mendoza",
    "radio interactiva Mendoza",
    "programas en vivo FM Brava",
    "radio que más crece en Mendoza",
    "Brava en vivo Argentina",
    "radio con buena vibra",
    "musica urbana en Mendoza",
    "radio juvenil en vivo",
    "Brava streaming online",
    "radio con temazos",
    "FM Brava la radio teen",
    "hits y programas juveniles Mendoza",
  ],
};
